project:
  type: website

website:
  title: "ISSS624_A01"
  navbar:
    left:
      - text: Hands-on Exercise
        menu: 
        - href: HandsOn_Exercise1/HandsOn_Exercise1.qmd
        - href: HandsOn_Exercise2/HandsOn_Ex02.qmd
        - href: HandsOn_Exercise3/HandsOn_Ex03.qmd
      - text: In Class Exercise
        menu: 
          - text: InClass Exercise Hunan Case Study.
          - href: InClass_Ex01/InClass_Hunan.qmd
      - text: Take Home Exercise
        menu: 
          - href: InClass_Ex02/Africa_Water/Take_Home_Ex1.qmd
          - href: TakeHome_Ex02/TakeHome_Ex02.qmd
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

