---
title: "ISSS624_A01"
---

# Welcome to Application of Geospatial Analytics Using R.

### 1. What is Geospatial Analytics ?

If I want to describe it in one line then I can say -

Geospatial Analytics is a Statistical Analysis of Geographical Information.

### 2. Why Geospatial Analytics is required ?

Internet and mobile phone revolution enabled easy access of GPS enabled data capturing devices to common man. There is therefore associated increase in demand for explicit spatial analysis of such data. Such analytics help policy makers, decision makers to understand underlying trends of socio-economic activities. If one wants to understand various aspects as mentioned below, then ***Geospatial Analytics*** is the key.

1.  Availability of affordable housing
2.  Availability of pre-schools, day-care facilities etc.
3.  Transportation (Urban and Transport Planning, Logistics etc.)
4.  Crime
5.  Pollution
6.  Geo-marketing (store location analysis)
7.  Emergency Planning
8.  Water resources analysis
9.  Pandemic Analysis

### 3. What is EPSG ?

EPSG stands for European Petroleum Survey Group and is an organization that maintains a geodetic parameter database with standard codes, the **EPSG codes**, for [coordinate systems](http://support.virtual-surveyor.com/support/solutions/articles/1000261350), [datums](http://support.virtual-surveyor.com/solution/articles/1000261330), [spheroids](http://support.virtual-surveyor.com/support/solutions/articles/1000261329), units and such alike. Additionally, this database contains the parameters for these objects or - if they cannot easily be expressed as values - at least references to where such parameters can be found. 

Every geographic object (coordinate system, spheroid, unit, etc.) gets assigned a unique number. The database is under active maintenance.

\
The coordinate system with its EPSG code is usually stored in the source file (GeoTIFF, Shapefile, LandXML, etc.)

### 4. What is WGS84 ?

World Geodetic System 84 (WGS 84) is based on a consistent set of constants and model parameters that describe the Earth's size, shape, and gravity and geomagnetic fields. WGS84 consists of a reference ellipsoid, a standard coordinate system, altitude data, and a geoid. The error of WGS84 is believed to be less than 2 centimeters to the center mass.

### 5. What is ESRI (Environmental Systems Research Institute, Inc.) Shapefile file and how it is used ?
